version: '3.8'

# network = 172.20.0.0/16
# gateway = 172.20.0.1
networks:
  frontend_network:
    external: true
    name: docker_frontend_network

services:
  web:
    image: frontend-angular
    container_name: frontend_angular
    networks:
      - frontend_network
